name: RocketJoin
author: Lorenzo0111
main: me.Lorenzo0111.RocketJoin.CustomJoinMessage
version: 1.4
api-version: 1.14
softdepend: [PlaceholderAPI]
commands:
  rocketjoin:
    description: RocketJoin main command!
    aliases: [rj, cjm]
permissions:
  rocketjoin.command:
    description: RocketJoin command permission!