name: RocketJoin
author: Lorenzo0111
main: me.lorenzo0111.rocketjoin.RocketJoin
version: 1.8.2
softdepend: [PlaceholderAPI]
commands:
  rocketjoin:
    description: RocketJoin main command!
    aliases: [rj, cjm]
permissions:
  rocketjoin.command:
    description: RocketJoin command permission!
  rocketjoin.update:
    description: Player with this permission can view available update message on join. If update-message is disabled in the config this permission doesn't work.
  rocketjoin.vip:
    description: RocketJoin vip permission
