name: RocketJoin
author: Lorenzo0111
main: me.lorenzo0111.rocketjoin.RocketJoinBukkit
version: @version@
api-version: 1.13
softdepend: [PlaceholderAPI]
commands:
  rocketjoin:
    description: RocketJoin main command!
    aliases: [rj, cjm]
permissions:
  rocketjoin.command:
    description: RocketJoin command permission!
  rocketjoin.update:
    description: Player with this permission can view available update message on join. If update-message is disabled in the config this permission doesn't work.
  rocketjoin.vip:
    description: RocketJoin vip permission
  rocketjoin.silent:
    description: If set, who has this permission will join without messages