name: CI

on:
  push:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew shadowJar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: RocketJoin
          path: |
            **/build/libs/*.jar
            !build/libs/*.jar